home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('user', views.user, name='user'),
    path('user/roomlist', views.roomlist, name='roomlist'),
    path('user/lablist', views.lablist, name='lablist'),
    path('user/doclist', views.doclist, name='doclist'),
    path('user/patientlist', views.patientlist, name='patientlist'),
    path('user/patientlist/bill', views.bill, name='bill'),
    path('user/profile', views.profile, name='profile'),
]

register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.register, name='register')
]

room/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.room, name='room'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('room/', include('room.urls')),
    path('doctor/', include('doctor.urls')),
    path('laboratory/', include('laboratory.urls')),
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    Name = models.CharField(max_length=50, unique=True, null=False)
    Image = models.ImageField(upload_to='pics', max_length=100)
    Description = models.TextField()
    Fees = models.PositiveIntegerField(null=False)

    def __str__(self):
        return str(self.id) + " - " + self.Name


class Bed(models.Model):
    RID = models.ForeignKey(Room, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)


class Department(models.Model):
    Name = models.CharField(max_length=50, unique=True, null=False)
    Description = models.TextField()

    def __str__(self):
        return str(self.id)


class Doctor(models.Model):
    Sex_Choices = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
    Username = models.CharField(max_length=10, null=True)
    Password = models.CharField(max_length=10, null=True)
    Name = models.CharField(max_length=50, null=False)
    Image = models.ImageField(upload_to='pics', max_length=100)
    DOB = models.DateField(null=True)
    Sex = models.CharField(max_length=6, null=True, choices=Sex_Choices)
    DID = models.ForeignKey(Department, on_delete=models.CASCADE)
    Address = models.TextField()
    Contact = models.PositiveIntegerField(null=False)
    Email = models.EmailField()
    Fees = models.PositiveIntegerField(null=False)
    
    def __str__(self):
        return str(self.id) + " - " + self.Name + " - " + self.DID.Name


class Laboratory(models.Model):
    Name = models.CharField(max_length=50, unique=True, null=False)
    Description = models.TextField()
    Fees = models.PositiveIntegerField(null=False)
    
    def __str__(self):
        return str(self.id) + " - " + self.Name


class Patient(models.Model):
    Sex_Choices = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
    Username = models.CharField(max_length=10, null=True)
    Password = models.CharField(max_length=10, null=True)
    Name = models.CharField(max_length=30, null=False)
    Image = models.ImageField(upload_to='pics', max_length=100)
    DOB = models.DateField(null=True)
    Age = models.PositiveIntegerField(null=False)
    Sex = models.CharField(max_length=6, null=False, choices=Sex_Choices)
    Address = models.TextField()
    Contact = models.PositiveIntegerField(null=False)
    Email = models.EmailField()
    DOJ = models.DateField(null=False)
    BID = models.ForeignKey(Bed, on_delete=models.CASCADE)
    DID = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id) + " - " + self.Name + " - " + self.DID.Name


class Report(models.Model):
    PID = models.ForeignKey(Patient, on_delete=models.CASCADE)
    LID = models.ForeignKey(Laboratory, on_delete=models.CASCADE)
    Date = models.DateField()

    def __str__(self):
        return str(self.id) + " - " + self.PID.Name + " - " + str(self.Date)


class Admin(models.Model):
    Sex_Choices = [('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')]
    Username = models.CharField(max_length=10, null=False)
    Password = models.CharField(max_length=10, null=False)
    Name = models.CharField(max_length=30, null=False)
    Image = models.ImageField(upload_to='pics', max_length=100)
    DOB = models.DateField(null=False)
    Sex = models.CharField(max_length=6, null=False, choices=Sex_Choices)
    Address = models.TextField()
    Contact = models.PositiveIntegerField(null=False)
    Email = models.EmailField()

    def __str__(self):
        return str(self.id) + " - " + self.Name

laboratory/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

# Create your models here.

room/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from home.models import *
from datetime import date

a = False
pos = ''

# Create your views here.
def home(request):
    global a
    a = False
    return render(request, 'login.html', {'a': a})

def user(request):
    global a
    global pos
    if a:
        return render(request, 'home.html', {'a': a, 'pos' : pos})
    else:
        try:
            user = str(request.POST['uname'])
            psw = request.POST['psw']
            pos = str(request.POST['position'])
            if pos == 'admin':
                a = Admin.objects.get(Username=user, Password=psw)
            elif pos == 'doctor':
                a = Doctor.objects.get(Username=user, Password=psw)
            elif pos == 'patient':
                a = Patient.objects.get(Username=user, Password=psw)
        except:
            a = False
            messages.info(request, "Invalid Credentials")
            return redirect("/")
        else:
            return render(request, 'home.html', {'a': a, 'pos' : pos})

def roomlist(request):
    global a
    try :
        i = request.POST['btn']
    except :
        i = 1
    finally :
        i = Room.objects.get(pk=i)
        r = Room.objects.all()
        return render(request, 'room.html', {'a': a, 'room' : r, 'i' :i})

def lablist(request):
    global a
    try :
        i = request.POST['btn']
    except :
        i = 1
    finally :
        i = Laboratory.objects.get(pk=i)
        l = Laboratory.objects.all()
        return render(request, 'laboratory.html', {'a': a, 'lab' : l, 'i' :i})

def doclist(request):
    global a
    try :
        i = request.POST['btn']
    except :
        i = 1
    finally :
        i = Department.objects.get(pk=i)
        dept = Department.objects.all()
        return render(request, 'doctor_list.html', {'a': a, 'dept' : dept, 'i': i})

def patientlist(request):
    global a
    global pos
    if pos == 'admin':
        pat = Patient.objects.all()
    elif pos == 'doctor':
        pat = a.patient_set.all()
    return render(request, 'patient_list.html', {'a': a, 'pat' : pat, 'pos' : pos})

def profile(request):
    global a
    return render(request, 'profile.html', {'a' : a})

def bill(request):
    global a
    global pos
    if pos == 'doctor':
        id = int(request.POST['btn'])
        p = Patient.objects.get(pk=id)
        return render(request, 'generate_bill.html', {'a': a, 'p' : p, 'pos' : pos})
    else:
        if pos == 'patient':
            p = a
        elif pos == 'admin':
            id = int(request.POST['btn'])
            p = Patient.objects.get(pk=id)
        
        #other charges
        d = date.today() - p.DOJ
        d = int(d.days)
        hc = d*200
        rc = d*int(p.BID.RID.Fees)
        dc = d*int(p.DID.Fees)

        #report charges
        r = p.report_set.all()
        trp = 0
        for i in r:
            trp+=int(i.LID.Fees)
        
        #total charges
        total = hc+rc+dc+trp

        return render(request, 'generate_bill.html', {'a': a, 'p' : p, 'pos' : pos, 'days': d, 'hos' : hc, 'room':rc, 'doc': dc, 'trp': trp, 'total': total})

laboratory/views.py
from django.shortcuts import render
from home.models import Laboratory

# Create your views here.
def laboratory(request):
    try :
        i = request.POST['btn']
    except :
        i = 1
    finally :
        i = Laboratory.objects.get(pk=i)
        l = Laboratory.objects.all()
        return render(request, 'laboratory.html', {'a': False, 'lab' : l, 'i' :i})

register/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from home.models import Admin

a = False

# Create your views here.
def register(request):
    global a
    if a:
        try:
            u = str(request.POST['username'])
            p1 = request.POST['pass1']
            p2 = request.POST['pass2']
            if p1 != p2:
                a = False
                messages.info(request, "Invalid Credentials.")
                return redirect("register")
            n = str(request.POST['name'])
            ad = str(request.POST['address'])
            d = request.POST['dob']
            s = request.POST['sex']
            c = request.POST['contact']
            e = request.POST['email']
            i = request.POST['image']
            user = Admin.objects.create(Username=u, Password=p1, Name=n, Image=i, Address=ad,
            DOB=d, Sex=s, Contact=c, Email=e)
        except:
            a = False
            messages.info(request, "Invalid Credentials.")
            return redirect("register")
        else:
            user.save()
            messages.info(request, "User Created Successfully!")
            return redirect("/")
    else:
        return render(request, 'register.html', {'a' : a})

room/views.py
from django.shortcuts import render
from home.models import Room

# Create your views here.
def room(request):
    try :
        i = request.POST['btn']
    except :
        i = 1
    finally :
        i = Room.objects.get(pk=i)
        r = Room.objects.all()
        return render(request, 'room.html', {'a': False, 'room' : r, 'i' :i})

templates/base.html
{% load static %}
<html>
    <head>
        <style>
            body {
				background-color: #E6E6FA;
				margin: 0%;
            }
            
            .text {
                background-color: black;
                width: 100%;
                height: 25%;
				color: white;
            }

            .text img {
				height:25%;
				margin-left: 20px;
            }

            .hms {
                color: white;
                font-size: 55px;
                font-family: "times new roman";
				font-weight: bold;
				margin-left: 50px;
            }

            .greet {
                font-family: "times new roman";
				color: white;
				font-size: 20px;
				margin-right: 30px;
			}

			.headicon {
				width: 100%;
				color: white;
				font-family: "times new roman";
				color: white;
				font-size: 25px;
				font-weight: bold;
			}

			.headicon td {
				width: 33.3%;
				vertical-align: top;
			}

			a {
				text-decoration: none;
				color: white;
			}

            footer {
				width: 100%;
				height: 50%;
				background-color: black;
				color: white;
			}

			.foot {
				width: 98%;
				color: white;
				margin-left: 10px;
            }

			.foot td:last-child {
				width: 25%;
			}

			.container img {
				height: 35px;
				width: 35px;
			}

			.footicon img {
				height: 20px;
				width: 20px;
			}

			.container1 img {
				height: 80px;
			}

        </style>
        {% block style %}
		{% endblock %}
    </head>
    <body>
        <table class="text">
            <tr>
                <td rowspan="2" width="10%">
                    <img src="{% static 'images\icon.png' %}">
                </td>
                <td>
                    <p align="left" class="hms">HOSPITAL MANAGEMENT SYSTEM</p>
                </td>
            </tr>
            <tr>
                <td style="vertical-align: top;">
                    <p align="right" class="greet">
						{% block greet %}
						{% if a %}
							Hello, {{ a.Name }}.
						{% else %}
						{% endif %}
						{% endblock %}
					</p>
                </td>
            </tr>
            <tr>
                <td colspan="2">
					{% block headericon %}
				{% if a %}
				<table align="center" class="headicon">
					<tr>
						{% block back %}
						{% endblock %}
						<td align="center">
							<a href="/user/profile">
								<div class="container">
									<img src="{% static 'images\profile.png' %}">
									Profile
								</div>							
							</a>
						</td>
						<td align="center">
							<a href="/">
								<div class="container">
									<img src="{% static 'images\logout.png' %}">
									Logout
								</div>
							</a>
						</td>
					</tr>
				</table>
				{% else %}
				<table align="center" class="headicon">
					<tr>
						<td align="center">
							<a href="/">
								<div class="container">
									<img src="{% static 'images\home.png' %}">
									Home
								</div>
							</a>
						</td>
				</table>
				{% endif %}
			{% endblock %}
                </td>
            </tr>
        </table>
        {% block content %}
		{% endblock %}
		<footer>
			
			<table align="center" class="foot">
				<th>
					<p align="left" style="font-size:45px; margin-left:10px; margin-top:20px">
						<strong>
							Hospital Management System
						</strong>
					</p>
				</th>
				<tr>
					<td align="left">
						<p style="font-size:25px;">
							Some text about who we are and what we do.<br>
							Hospital, an institution that is built, staffed, and equipped for the diagnosis of disease; for
							the treatment,<br>
							both medical and surgical, of the sick and the injured; and for their housing during this
							process.<br>
							The modern hospital also often serves as a centre for investigation and for teaching.
						</p>
					</td>
					<td align="left">
						<p style="font-size:25px">
							<strong>
								Contact Us
							</strong>
						</p>
						<p style="font-size:20px">
						<div class="footicon">
							<img src="{% static 'images\call.png' %}">
							+012-485247
							<br>
							<img src="{% static 'images\email.png' %}">
							ab@example.com
						</div>
						</p>
						<p>
						<div class="container1">
							<img src="{% static 'images\social.png' %}">
						</div>
						</p>
					</td>
				</tr>
			</table>
		</footer>
    </body>
</html>

templates/doctor_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<style>
		.main {
			width: 100%;
			padding: 10;
		}

		.main td:first-child {
			width: 30%;
		}

		.main td:last-child {
			vertical-align: top;
			padding-top: 30px;
		}

		.about {
			width: 90%;
			margin-left: 5%;
			font-size: 25px;
		}

		.about p {
			text-align: justify;
		}

		.type {
			background-color: black;
			color: white;
			font-size: 30px;
			font-weight: bold;
			width: 100%;
			padding: 10;
			text-align: left;
		}

		.edit {
			width: 90%;
			height: 50%;
			padding: 10px;
			border-spacing: 0 15px;
		}
	
		.edit tr {
			background-color: white;
		}
	
		.edit td:last-child {
			width: 60%;
			font-size: 20px;
		}
	
		.contain {
			font-size: 20px;
		}

		.contain img {
			height: 25px;
		}
	</style>
{% endblock %}

{% if a %}
	{% block back %}
		<td align="center">
			<a href="/user">
				<div class="container">
					<img src="{% static 'images\back.png' %}">
					Back
				</div>
			</a>
		</td>
	{% endblock %}
{% endif %}

{% block content %}
	<table class="main">
		<tr>
			<td>
				{% if a %}
				<form action="/user/doclist" method="POST">
				{% else %}
				<form action="/doctor/" method="POST">
				{% endif %}
					{% csrf_token %}
					{% for d in dept %}
					{% if d.id == i.id %}
					<p style="font-size: 30px; font-weight:bold; padding:10">{{ d.Name }}</p>
					{% else %}
					<button class="type" type="submit" name="btn" value="{{d.id}}"> {{ d.Name }} </button> <br>
					{% endif %}
					{% endfor %}
				</form>
			</td>
			<td>
				<div class="about">
					<h1>Department of {{ i.Name }} </h1>
					<p>{{ i.Description }}</p>
					<table class="edit" align="center">
						{% for d in i.doctor_set.all %}
						<tr>
							<td align="center">
								<div class="docimg">
									<img src="{{ d.Image.url }}" alt="doc">
								</div>
							</td>
							<td>
								<b style="font-size: 25px;">
									Dr. {{ d.Name }}
								</b>
								<br>
								<i style="font-size: 20px;">
									Department of {{ d.DID.Name }}
								</i>
								<br>
								<b style="font-size: 20px;">
									Fees: Rs. {{ d.Fees }}
								</b>
								<br>
								<br>
								<p>
								<div class="contain">
									<img src="{% static 'images\doc_address.png' %}">
									{{ d.Address}}
									<br>
									<img src="{% static 'images\doc_call.png' %}">
									+ 91 - {{ d.Contact }}
									<br>
									<img src="{% static 'images\doc_email.png' %}">
									{{ d.Email }}
								</div>
								</p>
							</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			</td>
		</tr>
	</table>
{% endblock %}

templates/generate_bill.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<style>
		.subhead {
			font-size: 20px;
			width: 90%;
			margin-left: 5%;
		}
	
		.subhead hr {
			border: 1px solid black;
		}

		/* Make the image responsive */
		.contain img {
			height: 250px;
		}

		.edit {
			width: 80%;
			height: 50%;
			padding: 10px;
			border-spacing: 0 15px;
			border-spacing: 0 15px;
			background-color: white;
		}

		.hosp {
			width: 80%;
			height: 50%;
			padding: 10px;
			border-spacing: 0 15px;
			background-color: white;
		}

		.hosp td {
			width: 50%;
			font-size: 20px;
		}

		.report {
			width: 80%;
			height: 30%;
			padding: 10px;
			border-spacing: 0 15px;
			background-color: white;
			border-collapse: collapse;
		}

		.report tr {
			border-bottom: 1px solid black;
		}

		.report tr:last-child {
			border-bottom: none;
		}

		.report td {
			width: 33.3%;
			font-size: 20px;
		}

		.desc {
			width: 60%;
			font-size: 20px;
		}

		/* Set a style for the submit button */
		.registerbtn {
			background-color: black;
			color: white;
			padding: 16px 20px;
			margin: 8px 0;
			border: none;
			cursor: pointer;
			width: 50%;
			font-size: 20;
		}

		.registerbtn:hover {
			opacity: 1;
		}

		/* Add a blue text color to links */
		a {
			color: white;
		}
	</style>
{% endblock %}

{% if user %}
	{% block back %}
		<td align="center">
			{% if pos == 'patient' %}
			<a href="/user">
			{% else %}
			<a href="/user/patientlist">
			{% endif %}
				<div class="container">
					<img src="{% static 'images\back.png' %}">
					Back
				</div>
			</a>
		</td>
	{% endblock %}
{% endif %}

{% block content %}
<div class="subhead">
    <p style="font-size: 35px; font-weight: bold">
		Patient Details
	</p>
	<hr>
</div>
	<table class="edit" align="center">
		<tr>
			<td align="center">
				<div class="contain">
					<img src="{{ p.Image.url }}" alt="doc">
				</div>
			</td>
			<td class="desc">
				<b style="font-size: 30px;">
					{{ p.Name }}
				</b>
				<br>
				<br>
				<b>
					Dr. {{ p.DID.Name }}
				</b>
				<br>
				<i>
					Department of {{ p.DID.DID.Name }}
				</i>
				<br>
				<br>
				<table width="100%">
					<th align="left" style="font-size: 20px;">
						<b>
							Date of Joining : {{ p.DOJ }}
						</b>
					</th>
					<tr>
						<td width="50%" style="font-size: 20px;">
							<p style="font-size:20px">
								<div class="container">
									<img src="{% static 'images\doc_call.png' %}">
									+ 91 {{ p.Contact }}
									<br>
									<img src="{% static 'images\doc_email.png' %}">
									{{ p.Email }}
								</div>
							</p>
						</td>
						<td style="font-size: 20px;">
							Sex : {{ p.Sex }}<br>
							Age : {{ p.Age }}<br>
							Room Type : {{ p.BID.RID.Name }}<br>
							Bed No. : {{ p.BID }}
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	{% if pos != 'doctor' %}
	<div class="subhead">
		<p style="font-size: 35px; font-weight: bold">
			Hospital Details
		</p>
		<hr>
	</div>
	<table class="hosp" align="center">
		<tr>
			<td align="right"><b>No. of days spend : </b></td>
			<td align="left">{{ days }} days</td>
		</tr>
		<tr>
			<td align="right"><b>Room Rent (per day) : </b></td>
			<td align="left">Rs. {{ p.BID.RID.Fees }}</td>
		</tr>
		<tr>
			<td align="right"><b>Doctor Fees (per day) : </b></td>
			<td align="left">Rs. {{ p.DID.Fees }}</td>
		</tr>
		<tr>
			<td align="right"><b>Hospital Charges (per day) : </b></td>
			<td align="left">Rs. 200</td>
		</tr>	 	 
	</table>
	{% endif %}
	<div class="subhead">
		<p style="font-size: 35px; font-weight: bold">
			Diagnostics Details
		</p>
		<hr>
	</div>
	<table class="report" align="center">
		<tr>
			<th align="center">REPORT DATE</th>
			<th align="center">TEST NAME</th>
			{% if pos != 'doctor' %}
			<th align="center">REPORT FEES</th>
			{% endif %}
		</tr>
		{% for report in p.report_set.all %}
		<tr>
			<td align="center">{{ report.Date }}</td>
			<td align="center">{{ report.LID.Name }}</td>
			{% if pos != 'doctor' %}
			<td align="center"> Rs. {{ report.LID.Fees }}</td>
			{% endif %}
		</tr>
		{% endfor %}
	</table>
	{% if pos != 'doctor' %}
	<table class="report"  align="center" style="height:10%">
		<tr>
			<td align="center"><b>Total Report Charges : Rs {{ trp }}</b></td>
		</tr>
	</table>
	<div class="subhead">
		<p style="font-size: 35px; font-weight: bold">
			Total Charges
		</p>
		<hr>
	</div>
	<table class="hosp" align="center">
		<tr>
			<td align="right"><b>Hospital Charges : </b></td>
			<td align="left">Rs. {{ hos }}</td>
		</tr>
		<tr>
			<td align="right"><b>Room Charges : </b></td>
			<td align="left">Rs. {{ room }}</td>
		</tr>
		<tr>
			<td align="right"><b>Doctor Charges : </b></td>
			<td align="left">Rs. {{ doc }}</td>
		</tr>
		<tr>
			<td align="right"><b>Report Charges : </b></td>
			<td align="left">Rs. {{ trp }}</td>
		</tr>
		<tr>
			<td align="right"><b>Total Bill : </b></td>
			<td align="left">Rs. {{ total }}</td>
		</tr>		 	 
	</table>
	{% endif %}
	<br>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
    .main {
        width: 80%;
        margin-left: 10%;
        margin-top: 15px;
        margin-bottom: 15px;
    }

    .main td {
        width: 50%;
        height: 50%;
        padding: 15px;
    }

    .btn {
        background-color: black;
        width: 90%;
        height: 100%;
        cursor: pointer;
    }

    .btn1 {
        background-color: black;
        width: 50%;
        height: 100%;
        cursor: pointer;
    }    

    .desc {
        width: 100%;
        color: white;
        font-size: 35px;
		font-weight: bold;
        font-family: 'bookman old style';
    }

    .desc td {
        padding: 25px;
    }

    .desc td:first-child {
        text-align: left;
        vertical-align: bottom;
    }

    .desc td:last-child {
        text-align: right;
        vertical-align: top;
    }

</style>
{% endblock %}

{% block content %}
<table class="main">
    <tr>
        <td>
            <a href="user/roomlist">
                <button class="btn">
                    <table class="desc" align="center">
                        <tr>
                            <td>
                                Rooms
                            </td>
                            <td>
                                <img src="{% static 'images\room.png' %}" height=100px>
                            </td>
                        </tr>
                    </table>
                </button>
            </a>
        </td>
        <td>
            <a href="user/doclist">
                <button  class="btn">
                    <table class="desc" align="center">
                        <tr>
                            <td>
                                Doctors
                            </td>
                            <td>
                                <img src="{% static 'images\doctor.png' %}" height=100px>
                            </td>
                        </tr>
                    </table>
                </button>
            </a>
        </td>
    </tr>
    <tr>
        <td>
            {% if pos == 'patient' %}
            <a href="user/patientlist/bill">
            {% else %}
            <a href="user/patientlist">
            {% endif %}
                <button  class="btn">
                    <table class="desc" align="center">
                        <tr>
                            <td>
                                {% if pos == 'admin' %}
                                All Patients
                                {% elif pos == 'doctor' %}
                                My Patients
                                {% elif pos == 'patient' %}
                                Bill Details
                                {% endif %}
                            </td>
                            <td>
                                {% if pos == 'patient' %}
                                <img src="{% static 'images\bill.png' %}" height=100px>
                                {% else %}
                                <img src="{% static 'images\patient.png' %}" height=100px>
                                {% endif %}
                            </td>
                        </tr>
                    </table>
                </button>
            </a>
        </td>
        <td>
            <a href="user/lablist">
                <button  class="btn">
                    <table class="desc" align="center">
                        <tr>
                            <td>
                                Diagnostics
                            </td>
                            <td>
                                <img src="{% static 'images\laboratory.png' %}" height=100px>
                            </td>
                        </tr>
                    </table>
                </button>
            </a>
        </td>
    </tr>
</table>
{% endblock %}

templates/laboratory.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<style>
		.main {
			width: 100%;
			padding: 10;
		}

		.main tr:first-child {
			text-align: justify;
			padding: 10;
		}

		.main tr:last-child {
			vertical-align: top;
			padding-top: 20px;
			text-align: justify;
			width: 33%;
		}

		.contain {
			width: 90%;
			margin-left: 5%;
			font-size: 25px;
			text-align: justify;
		}

		.type {
			background-color: black;
			color: white;
			font-size: 20px;
			font-weight: bold;
			width: fit-content;
			text-align: left;
		}
	</style>
{% endblock %}

{% if a %}
	{% block back %}
		<td align="center">
			<a href="/user">
				<div class="container">
					<img src="{% static 'images\back.png' %}">
					Back
				</div>
			</a>
		</td>
	{% endblock %}
{% endif %}

{% block content %}
	<table class="main">
		<tr>
			<td>
				{% if a %}
				<form action="/user/lablist" method="POST">
				{% else %}
				<form action="/laboratory/" method="POST">
				{% endif %}
					{% csrf_token %}
					{% for l in lab %}
					{% if l.id == i.id %}
					<font style="font-size: 20px; font-weight:bold; padding:10">{{ l.Name }}</font>
					{% else %}
					<button class="type" type="submit" name="btn" value="{{l.id}}"> {{ l.Name }} </button>
					{% endif %}
					{% endfor %}
				</form>
			</td>
		</tr>
		<tr>
			<td>
				<div class="contain">
					{{ i.Description }}<br><br>
					<b>Fees : </b>
					Rs.{{ i.Fees }}
				</div>
			</td>
		</tr>
	</table>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<style>
		/* Make the image responsive */
		.contain img {
			height: 250px;
		}

		.edit {
			width: 80%;
			height: 50%;
			padding: 10px;
			border-spacing: 0 15px;
		}

		.edit tr {
			background-color: white;
		}

		.desc {
			width: 60%;
			font-size: 25px;
		}
	</style>
{% endblock %}

{% block headericon %}
	<table align="center" class="headicon">
		<tr>
			<td align="center">
				<a href="/user">
					<div class="container">
						<img src="{% static 'images\back.png' %}">
						Back
					</div>
				</a>
			</td>
			<td align="center">
				<a href="/">
					<div class="container">
						<img src="{% static 'images\login.png' %}">
						Logout
					</div>
				</a>
			</td>
	</table>
{% endblock %}

{% block content %}
	<h1>
		<p align="center" style="font-size: 35px;">
			My Profile
		</p>
	</h1>
	<hr align="center" style="border: 1px solid black; width: 90%">
	<table class="edit" align="center">
		<tr>
			<td align="center">
				<div class="contain">
					<img src="{{ a.Image.url }}" alt="doc">
				</div>
			</td>
			<td class="desc">
				<b style="font-size: 35px;">
					{{ a.Name }}
				</b>
				<br>
				<p>
					<div class="container">
						<img src="{% static 'images\dob.png' %}">
						{{ a.DOB }}
						<br>
						<img src="{% static 'images\sex.png' %}">
						{{ a.Sex }}
						<br>
						<img src="{% static 'images\doc_address.png' %}">
						{{ a.Address }}
						<br>
						<img src="{% static 'images\doc_call.png' %}">
						+ 91 {{ a.Contact }}
						<br>
						<img src="{% static 'images\doc_email.png' %}">
						{{ a.Email }}
					</div>
				</p>
			</td>
		</tr>
	</table>
{% endblock %}